apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-simple-server-
spec:
  pipelineRef:
    name: python-build-containerize
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: repo-url
    value: https://github.com/unixunion/simple-server-k8s-test.git
  - name: revision
    value: main
  - name: image-reference
    value: registry.unixunion.org/sandbox/simple-server:dev
  - name: dockerfile
    value: ./Dockerfile